---
language: node_js

cache:
  bundler: true
  apt: true
  directories:
    - node_modules

node_js:
  - "0.10"

git:
  depth: 1

install: true
#  - npm install --production --loglevel warn

notifications:
  hipchat: Hh5Mwiy8zhd1LVPqg2hIgx9PSnP8GUjdoPWCwpG1@mfn
  email:
    on_success: never
