---
language: node_js

cache:
  bundler: true
  apt: true
  directories:
    - node_modules

node_js:
  - "0.10"

git:
  depth: 1

install: true
#  - npm install --production --loglevel warn
#  npm config set dev true
#  npm install vows -g
